apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: spc-multiple-secrets                   # name of the SecretProviderClass
spec:
  # Secret synchronization fields removed from SPC and moved to SecretSyncObject
  # secretObjects:                             # [OPTIONAL] SecretObject defines the desired state of synced K8s secret objects
  # - data:
  #  - key: username                           # data field to populate
  #    objectName: foo1                        # name of the mounted content to sync.
  #  secretName: foosecret                     # name of the Kubernetes Secret object
  #  type: Opaque                              # type of the Kubernetes Secret object e.g. Opaque, kubernetes.io/tls
  # ...
  provider: e2e-provider                       # name of the provider e.g. azure, gcp
  parameters:                                  # provider specific parameters
    objects: |                                 # [REQUIRED] objects to fetch from vault, specified as an array of objects.
      array:                                        # array of objects.
        - |
          objectName: <secret1-name-in-vault>       # name of the secret object
          objectType: secret                        # object types: secret, key or cert
        - |
          objectName: <secret1-name-in-vault>       # name of the secret object
          objectType: secret                        # object types: secret, key or cert