apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: spc-multiple-secrets                        # name of the SecretProviderClass
spec:
  provider: azure                                   # name of the provider
  parameters:
    clientID: "<client-id-for-workload-identity>"   # [OPTIONAL for Azure] used for azure authentication
    keyvaultName: "<key-vault-name>"                # name of the keyvault
    objects: |                                      # [REQUIRED] objects to fetch from keyvault, specified in an
      array:                                        # array             
        - |
          objectName: <secret1-name-in-key-vault>   # name of the secret object
          objectType: secret                        # object types: secret, key or cert
        - |
          objectName: <secret2-name-in-key-vault>   # name of the secret object
          objectType: secret                        # object types: secret, key or cert
          objectAlias: <secret2-object-alias>       # [OPTIONAL] object alias, default to object name
          objectVersion:                            # [OPTIONAL] object versions, default to latest if empty
    tenantId: "<tenant-id>"                         # [OPTIONAL for Azure] used for azure authentication