run:
  timeout: 5m
  go: "1.20"
  skip-files:
  - "zz_generated.*\\.go$"
  - "pkg/util/fileutil/atomic_writer.go"
  - "pkg/util/fileutil/atomic_writer_test.go"

linters-settings:
  gocritic:
    enabled-tags:
    - performance
  lll:
    line-length: 200
  misspell:
    locale: US
  staticcheck:
    go: "1.20"

linters:
  disable-all: true
  enable:
    - durationcheck
    - exportloopref
    - errcheck
    - errorlint
    - exhaustive
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - gosimple
    - govet
    - gosec
    - ineffassign
    - makezero
    - misspell
    - nilerr
    - revive
    - staticcheck
    - stylecheck
    - typecheck
    - unused
    - whitespace
  # Run with --fast=false for more extensive checks (enables all linters)
  fast: true

issues:
  # default: 50
  max-issues-per-linter: 0
  exclude-rules:
    - text: "unused-parameter: parameter '.*' seems to be unused, consider removing or renaming it as _"
      linters:
        - revive

  # default: 3
  max-same-issues: 0

severity:
  # default: ''
  default-severity: error
