version: "2"
run:
  go: "1.23"
  timeout: 5m
linters:
  default: none
  enable:
    - copyloopvar
    - durationcheck
    - errcheck
    - errorlint
    - exhaustive
    - goconst
    - gocritic
    - gocyclo
    - gosec
    - govet
    - ineffassign
    - makezero
    - misspell
    - nilerr
    - revive
    - staticcheck
    - unused
    - whitespace
  settings:
    gocritic:
      enabled-tags:
        - performance
    lll:
      line-length: 200
    misspell:
      locale: US
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - revive
        text: 'unused-parameter: parameter ''.*'' seems to be unused, consider removing or renaming it as _'
      - linters:
          - revive
        text: 'dot-imports: should not use dot imports'
        source: . "github.com/onsi/(ginkgo/v2|gomega)"
    paths:
      - zz_generated.*\.go$
      - pkg/util/fileutil/atomic_writer.go
      - pkg/util/fileutil/atomic_writer_test.go
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
severity:
  default: error
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - zz_generated.*\.go$
      - pkg/util/fileutil/atomic_writer.go
      - pkg/util/fileutil/atomic_writer_test.go
      - third_party$
      - builtin$
      - examples$
