run:
  timeout: 5m
  go: "1.24"

linters-settings:
  gocritic:
    enabled-tags:
    - performance
  lll:
    line-length: 200
  misspell:
    locale: US

linters:
  disable-all: true
  enable:
    - copyloopvar
    - durationcheck
    - errcheck
    - errorlint
    - exhaustive
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - gosimple
    - govet
    - gosec
    - ineffassign
    - makezero
    - misspell
    - nilerr
    - revive
    - staticcheck
    - stylecheck
    - typecheck
    - unused
    - whitespace
  # Run with --fast=false for more extensive checks (enables all linters)
  fast: true

issues:
  exclude-files:
    - "zz_generated.*\\.go$"
    - "pkg/util/fileutil/atomic_writer.go"
    - "pkg/util/fileutil/atomic_writer_test.go"
  max-issues-per-linter: 0
  exclude-rules:
    - text: "unused-parameter: parameter '.*' seems to be unused, consider removing or renaming it as _"
      linters:
        - revive
    - text: "dot-imports: should not use dot imports"
      linters:
        - revive
      source: ". \"github.com/onsi/(ginkgo/v2|gomega)\""

  # default: 3
  max-same-issues: 0

severity:
  # default: ''
  default-severity: error
