run:
  timeout: 5m
  skip-dirs:
  skip-files:
  - "zz_generated.*\\.go$"

linters:
  disable-all: true
  enable:
    - deadcode
    - gofmt
    - goimports
    - gosimple
    - revive
    - govet
    - gosec
    - ineffassign
    - misspell
    - unused
    - structcheck
    - varcheck
  # Run with --fast=false for more extensive checks (enables all linters)
  fast: true
