run:
  timeout: 5m
  skip-dirs: []
  skip-files:
  - "zz_generated.*\\.go$"

linters:
  disable-all: true
  enable:
    - deadcode
    - gofmt
    - goimports
    - gosimple
    - govet
    - gosec
    - ineffassign
    - misspell
    - revive
    - structcheck
    - unused
    - varcheck
  # Run with --fast=false for more extensive checks (enables all linters)
  fast: true

issues:
  # default: 50
  max-issues-per-linter: 0

  # default: 3
  max-same-issues: 0

severity:
  # default: ''
  default-severity: error
