# Netlify build instructions
[build]
    command = "make -C docs/book build"
    publish = "docs/book/book"

# Standard Netlify redirects
[[redirects]]
    from = "https://master--kubernetes-sigs-secrets-store-csi-driver.netlify.app/*"
    to = "https://master.secrets-store-csi-driver.sigs.k8s.io/:splat"
    status = 301
    force = true

# HTTP-to-HTTPS rules
[[redirects]]
    from = "http://master.secrets-store-csi-driver.sigs.k8s.io/*"
    to = "https://master.secrets-store-csi-driver.sigs.k8s.io/:splat"
    status = 301
    force = true

[[redirects]]
    from = "http://master--kubernetes-sigs-secrets-store-csi-driver.netlify.app/*"
    to = "http://master.secrets-store-csi-driver.sigs.k8s.io/:splat"
    status = 301
    force = true
