# This is the configuration file for the Secret Sync Controller. These values will be passed to the helm chart.
# The config map is an easy way to provide an example of the configuration.
# The user must configure:
#   the controllerName and controllerNamespace parameters
#   the list of Audiences: they should have the format tokenAudience<user-defined-name>: 'audience'
# The user should NOT configure:
#   the labelKey and labelValue parameters
#   the maxExpirationSeconds parameter
apiVersion: v1
kind: ConfigMap
metadata:
  name: "admission-policies-secret-sync-controller-config"
data:
  labelKey: 'secrets-sync-controller.k8s.io/managed'
  labelValue: ''
  controllerName: 'secret-sync-controller'
  controllerServiceAccountName: 'secret-sync-controller-sa'
  controllerNamespace: 'secret-sync-controller'
  tokenAudience1: 'api://TokenAudienceExample'
