# This is the config map for the deny policy. These values will be passed to the helm chart.
# The config map is an easy way to provide an example of the configuration.
# It is used to configure the controllerName, controllerNamespace parameters and the list of secret types to denny.
# The user must configure:
#   the controllerName and controllerNamespace parameters
#   the list of secret types to denny
apiVersion: v1
kind: ConfigMap
metadata:
  name: "admission-policies-secret-sync-controller-deny-config"
data:
  controllerName: 'secret-sync-controller'
  controllerNamespace: 'secret-sync-controller'
  secretTypeServiceAccountToken: 'kubernetes.io/service-account-token'
  