# This policy is used to restrict the types of secrets that the controller can create or update.
# It requires the parameter controllerName, controllerNamespace and the list of secret types to allow to be set in the
# ConfigMap admission-policies-secret-sync-controller-config.
# The user must configure:
#   the controllerName and controllerNamespace parameters
#   the list of secret types to allow
apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingAdmissionPolicy
metadata:
  name: "secret-sync-controller-create-update-policy"
spec:
  failurePolicy: Fail
  paramKind:
    apiVersion: v1
    kind: ConfigMap 
  matchConditions:
    - name: 'user-is-secret-sync-controller'
      expression: "request.userInfo.username == 'system:serviceaccount:'+params.data.controllerNamespace+':'+params.data.controllerName" #'system:serviceaccount:'+params.data.controllerNamespace+':'+params.data.controllerName
  matchConstraints:
    resourceRules:
    - apiGroups:   [""]
      apiVersions: ["v1"]
      operations:  ["CREATE", "UPDATE"]
      resources:   ["secrets"]
  variables:
  - name: hasOneSecretSyncOwner
    expression: "has(object.metadata.ownerReferences) && (size(object.metadata.ownerReferences) == 1 && object.metadata.ownerReferences.all(o, o.kind == 'SecretSync' && o.apiVersion.startsWith('secretsync.secret-sync.x-k8s.io/') && o.name == object.metadata.name))"
  - name: allowedSecretTypes
    expression: "params.data.exists_one(x, params.data[x] == object.type) ? true : false"
  validations:
  - expression: "variables.allowedSecretTypes == true && variables.hasOneSecretSyncOwner == true"
    message: "Only secrets with types defined in the config_allow_secret_types configmap are allowed"
    messageExpression: "string(params.data.controllerName)  + ' has failed to ' +  string(request.operation) + ' secret with ' + string(object.type) + ' type ' + 'in the ' + string(request.namespace) + ' namespace. The controller can only create or update secrets in the allowed types list with a single secretsync owner.'"
    reason: "Forbidden"