# This policy will deny updates to secrets that do not have the correct label.
# It requires the parameter controllerName and controllerNamespace to be set in the
# ConfigMap admission-policies-secret-sync-controller-config.
# The label key and value are set in the ConfigMap admission-policies-secret-sync-controller-allow-config.
# The label key and value shouldn't be changed by the user.
# The user must configure:
#   the controllerName and controllerNamespace parameters
apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingAdmissionPolicy
metadata:
  name: "secret-sync-controller-update-label-policy"
spec:
  failurePolicy: Fail
  paramKind:
    apiVersion: v1
    kind: ConfigMap 
  matchConditions:
    - name: 'userIsController'
      expression: "request.userInfo.username == 'system:serviceaccount:'+params.data.controllerNamespace+':'+params.data.controllerName"
  matchConstraints:
    resourceRules:
    - apiGroups:   [""]
      apiVersions: ["v1"]
      operations:  ["UPDATE"]
      resources:   ["secrets"]
  variables:
  - name: oldSecretHasLabels
    expression: "has(oldObject.metadata.labels) ? true : false"
  - name: oldSecretHasExpectedLabelKey
    expression: "variables.oldSecretHasLabels && ((params.data.labelKey in oldObject.metadata.labels) ? true : false)"
  - name: oldSecretHasExpectedLabelValue
    expression: "params.data.labelValue != null ? (variables.oldSecretHasExpectedLabelKey && ((params.data.labelValue == oldObject.metadata.labels[params.data.labelKey]) ? true : false)) : (oldObject.metadata.labels[params.data.labelKey] ? false : true)"
  validations:
  - expression: "variables.oldSecretHasExpectedLabelKey && variables.oldSecretHasExpectedLabelValue" # if the expression evaluates to false, the validation check is enforced according to the failurePolicy
    message: "Only secrets with the correct label can be updated"
    messageExpression: "string(params.data.controllerName)  + ' has failed to ' +  string(request.operation) + ' secret with ' + string(object.type) + ' type ' + 'in the ' + string(request.namespace) + ' namespace because it does not have the correct label. Delete the secret and force the controller to recreate it with the correct label.'"
    reason: "Invalid"
