/*
Copyright 2020 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"time"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
	v1alpha1 "sigs.k8s.io/secrets-store-csi-driver/apis/v1alpha1"
	scheme "sigs.k8s.io/secrets-store-csi-driver/pkg/client/clientset/versioned/scheme"
)

// SecretProviderClassPodStatusesGetter has a method to return a SecretProviderClassPodStatusInterface.
// A group's client should implement this interface.
type SecretProviderClassPodStatusesGetter interface {
	SecretProviderClassPodStatuses(namespace string) SecretProviderClassPodStatusInterface
}

// SecretProviderClassPodStatusInterface has methods to work with SecretProviderClassPodStatus resources.
type SecretProviderClassPodStatusInterface interface {
	Create(*v1alpha1.SecretProviderClassPodStatus) (*v1alpha1.SecretProviderClassPodStatus, error)
	Update(*v1alpha1.SecretProviderClassPodStatus) (*v1alpha1.SecretProviderClassPodStatus, error)
	UpdateStatus(*v1alpha1.SecretProviderClassPodStatus) (*v1alpha1.SecretProviderClassPodStatus, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.SecretProviderClassPodStatus, error)
	List(opts v1.ListOptions) (*v1alpha1.SecretProviderClassPodStatusList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.SecretProviderClassPodStatus, err error)
	SecretProviderClassPodStatusExpansion
}

// secretProviderClassPodStatuses implements SecretProviderClassPodStatusInterface
type secretProviderClassPodStatuses struct {
	client rest.Interface
	ns     string
}

// newSecretProviderClassPodStatuses returns a SecretProviderClassPodStatuses
func newSecretProviderClassPodStatuses(c *SecretsstoreV1alpha1Client, namespace string) *secretProviderClassPodStatuses {
	return &secretProviderClassPodStatuses{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the secretProviderClassPodStatus, and returns the corresponding secretProviderClassPodStatus object, and an error if there is any.
func (c *secretProviderClassPodStatuses) Get(name string, options v1.GetOptions) (result *v1alpha1.SecretProviderClassPodStatus, err error) {
	result = &v1alpha1.SecretProviderClassPodStatus{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("secretproviderclasspodstatuses").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of SecretProviderClassPodStatuses that match those selectors.
func (c *secretProviderClassPodStatuses) List(opts v1.ListOptions) (result *v1alpha1.SecretProviderClassPodStatusList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.SecretProviderClassPodStatusList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("secretproviderclasspodstatuses").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested secretProviderClassPodStatuses.
func (c *secretProviderClassPodStatuses) Watch(opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("secretproviderclasspodstatuses").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a secretProviderClassPodStatus and creates it.  Returns the server's representation of the secretProviderClassPodStatus, and an error, if there is any.
func (c *secretProviderClassPodStatuses) Create(secretProviderClassPodStatus *v1alpha1.SecretProviderClassPodStatus) (result *v1alpha1.SecretProviderClassPodStatus, err error) {
	result = &v1alpha1.SecretProviderClassPodStatus{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("secretproviderclasspodstatuses").
		Body(secretProviderClassPodStatus).
		Do().
		Into(result)
	return
}

// Update takes the representation of a secretProviderClassPodStatus and updates it. Returns the server's representation of the secretProviderClassPodStatus, and an error, if there is any.
func (c *secretProviderClassPodStatuses) Update(secretProviderClassPodStatus *v1alpha1.SecretProviderClassPodStatus) (result *v1alpha1.SecretProviderClassPodStatus, err error) {
	result = &v1alpha1.SecretProviderClassPodStatus{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("secretproviderclasspodstatuses").
		Name(secretProviderClassPodStatus.Name).
		Body(secretProviderClassPodStatus).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *secretProviderClassPodStatuses) UpdateStatus(secretProviderClassPodStatus *v1alpha1.SecretProviderClassPodStatus) (result *v1alpha1.SecretProviderClassPodStatus, err error) {
	result = &v1alpha1.SecretProviderClassPodStatus{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("secretproviderclasspodstatuses").
		Name(secretProviderClassPodStatus.Name).
		SubResource("status").
		Body(secretProviderClassPodStatus).
		Do().
		Into(result)
	return
}

// Delete takes name of the secretProviderClassPodStatus and deletes it. Returns an error if one occurs.
func (c *secretProviderClassPodStatuses) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("secretproviderclasspodstatuses").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *secretProviderClassPodStatuses) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("secretproviderclasspodstatuses").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched secretProviderClassPodStatus.
func (c *secretProviderClassPodStatuses) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.SecretProviderClassPodStatus, err error) {
	result = &v1alpha1.SecretProviderClassPodStatus{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("secretproviderclasspodstatuses").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
