apiVersion: secrets-store.csi.k8s.com/v1alpha1
kind: SecretProviderClass
metadata:
  name: azure-kvname-podid
spec:
  provider: azure
  parameters:
    usePodIdentity: "true"         # [OPTIONAL] if not provided, will default to "false"
    keyvaultName: "kvname"                # the name of the KeyVault
    objects:  |
      array:
        - |
          objectName: secret1
          objectType: secret        # object types: secret, key or cert
          objectVersion: ""         # [OPTIONAL] object versions, default to latest if empty
        - |
          objectName: key1
          objectType: key
          objectVersion: ""
    resourceGroup: "rg1"               # the resource group of the KeyVault
    subscriptionId: "subid"              # the subscription ID of the KeyVault
    tenantId: "tid"                    # the tenant ID of the KeyVault  
