/*
Copyright 2022 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1

import (
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
	apisv1 "sigs.k8s.io/secrets-store-csi-driver/apis/v1"
)

// SecretProviderClassPodStatusLister helps list SecretProviderClassPodStatuses.
// All objects returned here must be treated as read-only.
type SecretProviderClassPodStatusLister interface {
	// List lists all SecretProviderClassPodStatuses in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*apisv1.SecretProviderClassPodStatus, err error)
	// SecretProviderClassPodStatuses returns an object that can list and get SecretProviderClassPodStatuses.
	SecretProviderClassPodStatuses(namespace string) SecretProviderClassPodStatusNamespaceLister
	SecretProviderClassPodStatusListerExpansion
}

// secretProviderClassPodStatusLister implements the SecretProviderClassPodStatusLister interface.
type secretProviderClassPodStatusLister struct {
	listers.ResourceIndexer[*apisv1.SecretProviderClassPodStatus]
}

// NewSecretProviderClassPodStatusLister returns a new SecretProviderClassPodStatusLister.
func NewSecretProviderClassPodStatusLister(indexer cache.Indexer) SecretProviderClassPodStatusLister {
	return &secretProviderClassPodStatusLister{listers.New[*apisv1.SecretProviderClassPodStatus](indexer, apisv1.Resource("secretproviderclasspodstatus"))}
}

// SecretProviderClassPodStatuses returns an object that can list and get SecretProviderClassPodStatuses.
func (s *secretProviderClassPodStatusLister) SecretProviderClassPodStatuses(namespace string) SecretProviderClassPodStatusNamespaceLister {
	return secretProviderClassPodStatusNamespaceLister{listers.NewNamespaced[*apisv1.SecretProviderClassPodStatus](s.ResourceIndexer, namespace)}
}

// SecretProviderClassPodStatusNamespaceLister helps list and get SecretProviderClassPodStatuses.
// All objects returned here must be treated as read-only.
type SecretProviderClassPodStatusNamespaceLister interface {
	// List lists all SecretProviderClassPodStatuses in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*apisv1.SecretProviderClassPodStatus, err error)
	// Get retrieves the SecretProviderClassPodStatus from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*apisv1.SecretProviderClassPodStatus, error)
	SecretProviderClassPodStatusNamespaceListerExpansion
}

// secretProviderClassPodStatusNamespaceLister implements the SecretProviderClassPodStatusNamespaceLister
// interface.
type secretProviderClassPodStatusNamespaceLister struct {
	listers.ResourceIndexer[*apisv1.SecretProviderClassPodStatus]
}
