/*
Copyright 2022 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	context "context"

	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
	apisv1 "sigs.k8s.io/secrets-store-csi-driver/apis/v1"
	scheme "sigs.k8s.io/secrets-store-csi-driver/pkg/client/clientset/versioned/scheme"
)

// SecretProviderClassesGetter has a method to return a SecretProviderClassInterface.
// A group's client should implement this interface.
type SecretProviderClassesGetter interface {
	SecretProviderClasses(namespace string) SecretProviderClassInterface
}

// SecretProviderClassInterface has methods to work with SecretProviderClass resources.
type SecretProviderClassInterface interface {
	Create(ctx context.Context, secretProviderClass *apisv1.SecretProviderClass, opts metav1.CreateOptions) (*apisv1.SecretProviderClass, error)
	Update(ctx context.Context, secretProviderClass *apisv1.SecretProviderClass, opts metav1.UpdateOptions) (*apisv1.SecretProviderClass, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, secretProviderClass *apisv1.SecretProviderClass, opts metav1.UpdateOptions) (*apisv1.SecretProviderClass, error)
	Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error
	Get(ctx context.Context, name string, opts metav1.GetOptions) (*apisv1.SecretProviderClass, error)
	List(ctx context.Context, opts metav1.ListOptions) (*apisv1.SecretProviderClassList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *apisv1.SecretProviderClass, err error)
	SecretProviderClassExpansion
}

// secretProviderClasses implements SecretProviderClassInterface
type secretProviderClasses struct {
	*gentype.ClientWithList[*apisv1.SecretProviderClass, *apisv1.SecretProviderClassList]
}

// newSecretProviderClasses returns a SecretProviderClasses
func newSecretProviderClasses(c *SecretsstoreV1Client, namespace string) *secretProviderClasses {
	return &secretProviderClasses{
		gentype.NewClientWithList[*apisv1.SecretProviderClass, *apisv1.SecretProviderClassList](
			"secretproviderclasses",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *apisv1.SecretProviderClass { return &apisv1.SecretProviderClass{} },
			func() *apisv1.SecretProviderClassList { return &apisv1.SecretProviderClassList{} },
		),
	}
}
