/*
Copyright 2022 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	context "context"

	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
	apisv1 "sigs.k8s.io/secrets-store-csi-driver/apis/v1"
	scheme "sigs.k8s.io/secrets-store-csi-driver/pkg/client/clientset/versioned/scheme"
)

// SecretProviderClassPodStatusesGetter has a method to return a SecretProviderClassPodStatusInterface.
// A group's client should implement this interface.
type SecretProviderClassPodStatusesGetter interface {
	SecretProviderClassPodStatuses(namespace string) SecretProviderClassPodStatusInterface
}

// SecretProviderClassPodStatusInterface has methods to work with SecretProviderClassPodStatus resources.
type SecretProviderClassPodStatusInterface interface {
	Create(ctx context.Context, secretProviderClassPodStatus *apisv1.SecretProviderClassPodStatus, opts metav1.CreateOptions) (*apisv1.SecretProviderClassPodStatus, error)
	Update(ctx context.Context, secretProviderClassPodStatus *apisv1.SecretProviderClassPodStatus, opts metav1.UpdateOptions) (*apisv1.SecretProviderClassPodStatus, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, secretProviderClassPodStatus *apisv1.SecretProviderClassPodStatus, opts metav1.UpdateOptions) (*apisv1.SecretProviderClassPodStatus, error)
	Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error
	Get(ctx context.Context, name string, opts metav1.GetOptions) (*apisv1.SecretProviderClassPodStatus, error)
	List(ctx context.Context, opts metav1.ListOptions) (*apisv1.SecretProviderClassPodStatusList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *apisv1.SecretProviderClassPodStatus, err error)
	SecretProviderClassPodStatusExpansion
}

// secretProviderClassPodStatuses implements SecretProviderClassPodStatusInterface
type secretProviderClassPodStatuses struct {
	*gentype.ClientWithList[*apisv1.SecretProviderClassPodStatus, *apisv1.SecretProviderClassPodStatusList]
}

// newSecretProviderClassPodStatuses returns a SecretProviderClassPodStatuses
func newSecretProviderClassPodStatuses(c *SecretsstoreV1Client, namespace string) *secretProviderClassPodStatuses {
	return &secretProviderClassPodStatuses{
		gentype.NewClientWithList[*apisv1.SecretProviderClassPodStatus, *apisv1.SecretProviderClassPodStatusList](
			"secretproviderclasspodstatuses",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *apisv1.SecretProviderClassPodStatus { return &apisv1.SecretProviderClassPodStatus{} },
			func() *apisv1.SecretProviderClassPodStatusList { return &apisv1.SecretProviderClassPodStatusList{} },
		),
	}
}
