/*
Copyright 2020 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"context"
	"time"

	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
	v1 "sigs.k8s.io/secrets-store-csi-driver/apis/v1"
	scheme "sigs.k8s.io/secrets-store-csi-driver/pkg/client/clientset/versioned/scheme"
)

// SecretProviderClassesGetter has a method to return a SecretProviderClassInterface.
// A group's client should implement this interface.
type SecretProviderClassesGetter interface {
	SecretProviderClasses(namespace string) SecretProviderClassInterface
}

// SecretProviderClassInterface has methods to work with SecretProviderClass resources.
type SecretProviderClassInterface interface {
	Create(ctx context.Context, secretProviderClass *v1.SecretProviderClass, opts metav1.CreateOptions) (*v1.SecretProviderClass, error)
	Update(ctx context.Context, secretProviderClass *v1.SecretProviderClass, opts metav1.UpdateOptions) (*v1.SecretProviderClass, error)
	UpdateStatus(ctx context.Context, secretProviderClass *v1.SecretProviderClass, opts metav1.UpdateOptions) (*v1.SecretProviderClass, error)
	Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error
	Get(ctx context.Context, name string, opts metav1.GetOptions) (*v1.SecretProviderClass, error)
	List(ctx context.Context, opts metav1.ListOptions) (*v1.SecretProviderClassList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.SecretProviderClass, err error)
	SecretProviderClassExpansion
}

// secretProviderClasses implements SecretProviderClassInterface
type secretProviderClasses struct {
	client rest.Interface
	ns     string
}

// newSecretProviderClasses returns a SecretProviderClasses
func newSecretProviderClasses(c *SecretsstoreV1Client, namespace string) *secretProviderClasses {
	return &secretProviderClasses{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the secretProviderClass, and returns the corresponding secretProviderClass object, and an error if there is any.
func (c *secretProviderClasses) Get(ctx context.Context, name string, options metav1.GetOptions) (result *v1.SecretProviderClass, err error) {
	result = &v1.SecretProviderClass{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("secretproviderclasses").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of SecretProviderClasses that match those selectors.
func (c *secretProviderClasses) List(ctx context.Context, opts metav1.ListOptions) (result *v1.SecretProviderClassList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1.SecretProviderClassList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("secretproviderclasses").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested secretProviderClasses.
func (c *secretProviderClasses) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("secretproviderclasses").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a secretProviderClass and creates it.  Returns the server's representation of the secretProviderClass, and an error, if there is any.
func (c *secretProviderClasses) Create(ctx context.Context, secretProviderClass *v1.SecretProviderClass, opts metav1.CreateOptions) (result *v1.SecretProviderClass, err error) {
	result = &v1.SecretProviderClass{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("secretproviderclasses").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(secretProviderClass).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a secretProviderClass and updates it. Returns the server's representation of the secretProviderClass, and an error, if there is any.
func (c *secretProviderClasses) Update(ctx context.Context, secretProviderClass *v1.SecretProviderClass, opts metav1.UpdateOptions) (result *v1.SecretProviderClass, err error) {
	result = &v1.SecretProviderClass{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("secretproviderclasses").
		Name(secretProviderClass.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(secretProviderClass).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *secretProviderClasses) UpdateStatus(ctx context.Context, secretProviderClass *v1.SecretProviderClass, opts metav1.UpdateOptions) (result *v1.SecretProviderClass, err error) {
	result = &v1.SecretProviderClass{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("secretproviderclasses").
		Name(secretProviderClass.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(secretProviderClass).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the secretProviderClass and deletes it. Returns an error if one occurs.
func (c *secretProviderClasses) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("secretproviderclasses").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *secretProviderClasses) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("secretproviderclasses").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched secretProviderClass.
func (c *secretProviderClasses) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.SecretProviderClass, err error) {
	result = &v1.SecretProviderClass{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("secretproviderclasses").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
