kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-vault
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 1Gi
  volumeName: pv-vault
  storageClassName: ""
