//
//Copyright 2020 The Kubernetes Authors.
//
//Licensed under the Apache License, Version 2.0 (the "License");
//you may not use this file except in compliance with the License.
//You may obtain a copy of the License at
//
//http://www.apache.org/licenses/LICENSE-2.0
//
//Unless required by applicable law or agreed to in writing, software
//distributed under the License is distributed on an "AS IS" BASIS,
//WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//See the License for the specific language governing permissions and
//limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11-devel
// 	protoc        v3.20.1
// source: provider/v1alpha1/service.proto

package v1alpha1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type VersionRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Version of the Secrets Store CSI Driver
	Version       string `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VersionRequest) Reset() {
	*x = VersionRequest{}
	mi := &file_provider_v1alpha1_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VersionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VersionRequest) ProtoMessage() {}

func (x *VersionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_provider_v1alpha1_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VersionRequest.ProtoReflect.Descriptor instead.
func (*VersionRequest) Descriptor() ([]byte, []int) {
	return file_provider_v1alpha1_service_proto_rawDescGZIP(), []int{0}
}

func (x *VersionRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type VersionResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Version of the Secrets Store CSI Driver
	Version string `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	// Name of the Secrets Store CSI Driver Provider
	RuntimeName string `protobuf:"bytes,2,opt,name=runtime_name,json=runtimeName,proto3" json:"runtime_name,omitempty"`
	// Version of the Secrets Store CSI Driver Provider. The string must be semver-compatible.
	RuntimeVersion string `protobuf:"bytes,3,opt,name=runtime_version,json=runtimeVersion,proto3" json:"runtime_version,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *VersionResponse) Reset() {
	*x = VersionResponse{}
	mi := &file_provider_v1alpha1_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VersionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VersionResponse) ProtoMessage() {}

func (x *VersionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_provider_v1alpha1_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VersionResponse.ProtoReflect.Descriptor instead.
func (*VersionResponse) Descriptor() ([]byte, []int) {
	return file_provider_v1alpha1_service_proto_rawDescGZIP(), []int{1}
}

func (x *VersionResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *VersionResponse) GetRuntimeName() string {
	if x != nil {
		return x.RuntimeName
	}
	return ""
}

func (x *VersionResponse) GetRuntimeVersion() string {
	if x != nil {
		return x.RuntimeVersion
	}
	return ""
}

type MountRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Attributes is the parameters field defined in the SecretProviderClass
	Attributes string `protobuf:"bytes,1,opt,name=attributes,proto3" json:"attributes,omitempty"`
	// Secrets is the secret content referenced in nodePublishSecretRef secret data
	Secrets string `protobuf:"bytes,2,opt,name=secrets,proto3" json:"secrets,omitempty"`
	// TargetPath is the path to which the volume will be published
	// TODO(tam7t): deprecate
	TargetPath string `protobuf:"bytes,3,opt,name=target_path,json=targetPath,proto3" json:"target_path,omitempty"`
	// Permission is the file permissions
	// TODO(tam7t): deprecate
	Permission string `protobuf:"bytes,4,opt,name=permission,proto3" json:"permission,omitempty"`
	// CurrentObjectVersion is the list of objects and their versions that's
	// currently mounted in the pod
	CurrentObjectVersion []*ObjectVersion `protobuf:"bytes,5,rep,name=current_object_version,json=currentObjectVersion,proto3" json:"current_object_version,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *MountRequest) Reset() {
	*x = MountRequest{}
	mi := &file_provider_v1alpha1_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MountRequest) ProtoMessage() {}

func (x *MountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_provider_v1alpha1_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MountRequest.ProtoReflect.Descriptor instead.
func (*MountRequest) Descriptor() ([]byte, []int) {
	return file_provider_v1alpha1_service_proto_rawDescGZIP(), []int{2}
}

func (x *MountRequest) GetAttributes() string {
	if x != nil {
		return x.Attributes
	}
	return ""
}

func (x *MountRequest) GetSecrets() string {
	if x != nil {
		return x.Secrets
	}
	return ""
}

func (x *MountRequest) GetTargetPath() string {
	if x != nil {
		return x.TargetPath
	}
	return ""
}

func (x *MountRequest) GetPermission() string {
	if x != nil {
		return x.Permission
	}
	return ""
}

func (x *MountRequest) GetCurrentObjectVersion() []*ObjectVersion {
	if x != nil {
		return x.CurrentObjectVersion
	}
	return nil
}

type MountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ObjectVersion []*ObjectVersion       `protobuf:"bytes,1,rep,name=object_version,json=objectVersion,proto3" json:"object_version,omitempty"`
	Error         *Error                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	// files contains the entire mount volume filesystem.
	//
	// The total size of all files should not exceed 1MiB or syncing to
	// Kubernetes Secrets will fail. If the contents of all files exceeds
	// 4MiB then requests could fail unless MaxCallRecvMsgSize is increased.
	Files         []*File `protobuf:"bytes,3,rep,name=files,proto3" json:"files,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MountResponse) Reset() {
	*x = MountResponse{}
	mi := &file_provider_v1alpha1_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MountResponse) ProtoMessage() {}

func (x *MountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_provider_v1alpha1_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MountResponse.ProtoReflect.Descriptor instead.
func (*MountResponse) Descriptor() ([]byte, []int) {
	return file_provider_v1alpha1_service_proto_rawDescGZIP(), []int{3}
}

func (x *MountResponse) GetObjectVersion() []*ObjectVersion {
	if x != nil {
		return x.ObjectVersion
	}
	return nil
}

func (x *MountResponse) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *MountResponse) GetFiles() []*File {
	if x != nil {
		return x.Files
	}
	return nil
}

// File holds secret file contents and location in the mount path to write the
// file.
type File struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The relative path of the file within the mount.
	// May not be an absolute path.
	// May not contain the path element '..'.
	// May not start with the string '..'.
	Path string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	// The mode bits used to set permissions on this file.
	// Must be a decimal value between 0 and 511.
	Mode int32 `protobuf:"varint,2,opt,name=mode,proto3" json:"mode,omitempty"`
	// The file contents.
	Contents      []byte `protobuf:"bytes,3,opt,name=contents,proto3" json:"contents,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *File) Reset() {
	*x = File{}
	mi := &file_provider_v1alpha1_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *File) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*File) ProtoMessage() {}

func (x *File) ProtoReflect() protoreflect.Message {
	mi := &file_provider_v1alpha1_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use File.ProtoReflect.Descriptor instead.
func (*File) Descriptor() ([]byte, []int) {
	return file_provider_v1alpha1_service_proto_rawDescGZIP(), []int{4}
}

func (x *File) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *File) GetMode() int32 {
	if x != nil {
		return x.Mode
	}
	return 0
}

func (x *File) GetContents() []byte {
	if x != nil {
		return x.Contents
	}
	return nil
}

type ObjectVersion struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Id is the object UID that is fetched from external secrets store
	// The Id should be unique. If multiple objects fetched from the secrets
	// store contain the same name, the provider should return a uid. This will
	// be populated in the SecretProviderClassPodStatus and sent back to the
	// provider as part of rotation reconcile
	// Example: secret/secret1, key/secret1, projects/$PROJECT_ID/secrets/secret1
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Version is the object version that is fetched from external secrets store
	Version       string `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ObjectVersion) Reset() {
	*x = ObjectVersion{}
	mi := &file_provider_v1alpha1_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ObjectVersion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObjectVersion) ProtoMessage() {}

func (x *ObjectVersion) ProtoReflect() protoreflect.Message {
	mi := &file_provider_v1alpha1_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObjectVersion.ProtoReflect.Descriptor instead.
func (*ObjectVersion) Descriptor() ([]byte, []int) {
	return file_provider_v1alpha1_service_proto_rawDescGZIP(), []int{5}
}

func (x *ObjectVersion) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ObjectVersion) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type Error struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Code is the error code that the provider can return which will be used for publishing metrics
	Code          string `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Error) Reset() {
	*x = Error{}
	mi := &file_provider_v1alpha1_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_provider_v1alpha1_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_provider_v1alpha1_service_proto_rawDescGZIP(), []int{6}
}

func (x *Error) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

var File_provider_v1alpha1_service_proto protoreflect.FileDescriptor

const file_provider_v1alpha1_service_proto_rawDesc = "" +
	"\n" +
	"\x1fprovider/v1alpha1/service.proto\x12\bv1alpha1\"*\n" +
	"\x0eVersionRequest\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\"w\n" +
	"\x0fVersionResponse\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12!\n" +
	"\fruntime_name\x18\x02 \x01(\tR\vruntimeName\x12'\n" +
	"\x0fruntime_version\x18\x03 \x01(\tR\x0eruntimeVersion\"\xd8\x01\n" +
	"\fMountRequest\x12\x1e\n" +
	"\n" +
	"attributes\x18\x01 \x01(\tR\n" +
	"attributes\x12\x18\n" +
	"\asecrets\x18\x02 \x01(\tR\asecrets\x12\x1f\n" +
	"\vtarget_path\x18\x03 \x01(\tR\n" +
	"targetPath\x12\x1e\n" +
	"\n" +
	"permission\x18\x04 \x01(\tR\n" +
	"permission\x12M\n" +
	"\x16current_object_version\x18\x05 \x03(\v2\x17.v1alpha1.ObjectVersionR\x14currentObjectVersion\"\x9c\x01\n" +
	"\rMountResponse\x12>\n" +
	"\x0eobject_version\x18\x01 \x03(\v2\x17.v1alpha1.ObjectVersionR\robjectVersion\x12%\n" +
	"\x05error\x18\x02 \x01(\v2\x0f.v1alpha1.ErrorR\x05error\x12$\n" +
	"\x05files\x18\x03 \x03(\v2\x0e.v1alpha1.FileR\x05files\"J\n" +
	"\x04File\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x12\n" +
	"\x04mode\x18\x02 \x01(\x05R\x04mode\x12\x1a\n" +
	"\bcontents\x18\x03 \x01(\fR\bcontents\"9\n" +
	"\rObjectVersion\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\"\x1b\n" +
	"\x05Error\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code2\x91\x01\n" +
	"\x11CSIDriverProvider\x12@\n" +
	"\aVersion\x12\x18.v1alpha1.VersionRequest\x1a\x19.v1alpha1.VersionResponse\"\x00\x12:\n" +
	"\x05Mount\x12\x16.v1alpha1.MountRequest\x1a\x17.v1alpha1.MountResponse\"\x00B\x15Z\x13./provider/v1alpha1b\x06proto3"

var (
	file_provider_v1alpha1_service_proto_rawDescOnce sync.Once
	file_provider_v1alpha1_service_proto_rawDescData []byte
)

func file_provider_v1alpha1_service_proto_rawDescGZIP() []byte {
	file_provider_v1alpha1_service_proto_rawDescOnce.Do(func() {
		file_provider_v1alpha1_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_provider_v1alpha1_service_proto_rawDesc), len(file_provider_v1alpha1_service_proto_rawDesc)))
	})
	return file_provider_v1alpha1_service_proto_rawDescData
}

var file_provider_v1alpha1_service_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_provider_v1alpha1_service_proto_goTypes = []any{
	(*VersionRequest)(nil),  // 0: v1alpha1.VersionRequest
	(*VersionResponse)(nil), // 1: v1alpha1.VersionResponse
	(*MountRequest)(nil),    // 2: v1alpha1.MountRequest
	(*MountResponse)(nil),   // 3: v1alpha1.MountResponse
	(*File)(nil),            // 4: v1alpha1.File
	(*ObjectVersion)(nil),   // 5: v1alpha1.ObjectVersion
	(*Error)(nil),           // 6: v1alpha1.Error
}
var file_provider_v1alpha1_service_proto_depIdxs = []int32{
	5, // 0: v1alpha1.MountRequest.current_object_version:type_name -> v1alpha1.ObjectVersion
	5, // 1: v1alpha1.MountResponse.object_version:type_name -> v1alpha1.ObjectVersion
	6, // 2: v1alpha1.MountResponse.error:type_name -> v1alpha1.Error
	4, // 3: v1alpha1.MountResponse.files:type_name -> v1alpha1.File
	0, // 4: v1alpha1.CSIDriverProvider.Version:input_type -> v1alpha1.VersionRequest
	2, // 5: v1alpha1.CSIDriverProvider.Mount:input_type -> v1alpha1.MountRequest
	1, // 6: v1alpha1.CSIDriverProvider.Version:output_type -> v1alpha1.VersionResponse
	3, // 7: v1alpha1.CSIDriverProvider.Mount:output_type -> v1alpha1.MountResponse
	6, // [6:8] is the sub-list for method output_type
	4, // [4:6] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_provider_v1alpha1_service_proto_init() }
func file_provider_v1alpha1_service_proto_init() {
	if File_provider_v1alpha1_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_provider_v1alpha1_service_proto_rawDesc), len(file_provider_v1alpha1_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_provider_v1alpha1_service_proto_goTypes,
		DependencyIndexes: file_provider_v1alpha1_service_proto_depIdxs,
		MessageInfos:      file_provider_v1alpha1_service_proto_msgTypes,
	}.Build()
	File_provider_v1alpha1_service_proto = out.File
	file_provider_v1alpha1_service_proto_goTypes = nil
	file_provider_v1alpha1_service_proto_depIdxs = nil
}
