name: e2e_mock_provider_tests

on:
  workflow_dispatch:
    inputs:
      registry:
        description: 'Registry for pulling images'
        required: true
        default: 'gcr.io/k8s-staging-csi-secrets-store'
      driverImageName:
        description: 'Secret Store CSI driver image name'
        required: true
        default: 'driver'
      crdImageName:
        description: 'Secret Store CSI driver CRD image name'
        required: true
        default: 'driver-crds'
      imageVersion:
        description: 'image version for Secret Store CSI driver and CRDs'
        required: true
        default: 'v1.CHANGE_ME'

permissions:
  contents: read

jobs:
  e2e-test:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    strategy:
      matrix:
        KUBERNETES_VERSION: ["v1.33.7", "v1.34.3", "v1.35.1"]
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@8d3c67de8e2fe68ef647c8db1e6a09f647780f40 # v2.19.0
        with:
          egress-policy: audit
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          submodules: true
          fetch-depth: 0
          persist-credentials: false
      - name: Setup BATS
        uses: mig4/setup-bats@af9a00deb21b5d795cabfeaa8d9060410377686d # v1.2.0
        with:
          bats-version: 1.4.1
      - name: Setup Kind
        run: |
          curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.31.0/kind-linux-amd64
          chmod +x ./kind
          sudo mv ./kind /usr/local/bin/kind
          kind create cluster --image "kindest/node:${{ matrix.KUBERNETES_VERSION }}"
      - name: Test
        run: |
          # GH action sets this var by default. We need to explicitly unset it so that build commit hash is not appended to image tag.
          unset CI

          make e2e-helm-deploy e2e-mock-provider-container e2e-provider-deploy e2e-provider
        env:
          REGISTRY: ${{ github.event.inputs.registry }}
          IMAGE_NAME: ${{ github.event.inputs.driverImageName }}
          CRD_IMAGE_NAME: ${{ github.event.inputs.crdImageName }}
          IMAGE_VERSION: ${{ github.event.inputs.imageVersion }}
