name: Check Markdown links

on:
  push:
    paths:
      - "**.md"
    branches:
    - main
  pull_request:
    branches:
    - main
    paths:
    - "**.md"
  schedule:
    - cron: "0 9 * * *"

permissions:
  contents: read

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@8d3c67de8e2fe68ef647c8db1e6a09f647780f40 # v2.19.0
      with:
        egress-policy: audit
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        persist-credentials: false
    - uses: gaurav-nelson/github-action-markdown-link-check@3c3b66f1f7d0900e37b71eca45b63ea9eedfce31 # 1.0.17
      with:
        # this will only show errors in the output
        use-quiet-mode: 'yes'
        # this will show detailed HTTP status for checked links
        use-verbose-mode: 'yes'
        config-file: .markdownlinkcheck.json
