name: Check Markdown links

on:
  push:
    paths:
      - "**.md"
    branches:
    - main
  pull_request:
    branches:
    - main
    paths:
    - "**.md"
  schedule:
    - cron: "0 9 * * *"

permissions:
  contents: read

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@9af89fc71515a100421586dfdb3dc9c984fbf411 # v2.19.4
      with:
        egress-policy: audit
    - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      with:
        persist-credentials: false
    - uses: gaurav-nelson/github-action-markdown-link-check@3c3b66f1f7d0900e37b71eca45b63ea9eedfce31 # 1.0.17
      with:
        # this will only show errors in the output
        use-quiet-mode: 'yes'
        # this will show detailed HTTP status for checked links
        use-verbose-mode: 'yes'
        config-file: .markdownlinkcheck.json
