name: Check Markdown links

on:
  push:
    paths:
      - "**.md"
    branches:
    - main
  pull_request:
    branches:
    - main
    paths:
    - "**.md"
  schedule:
    - cron: "0 9 * * *"

permissions:
  contents: read

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@e14015d583714f6e62063499dc959a02595150a1 # v2.21.1
      with:
        egress-policy: audit
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        persist-credentials: false
    - uses: gaurav-nelson/github-action-markdown-link-check@3c3b66f1f7d0900e37b71eca45b63ea9eedfce31 # 1.0.17
      with:
        # this will only show errors in the output
        use-quiet-mode: 'yes'
        # this will show detailed HTTP status for checked links
        use-verbose-mode: 'yes'
        config-file: .markdownlinkcheck.json
