name: scan_vulns

on:
  push:
    paths-ignore:
    - "docs/**"
    - "**.md"
  pull_request:
    paths-ignore:
    - "docs/**"
    - "**.md"

permissions:
  contents: read

jobs:
  govulncheck:
    name: "Run govulncheck"
    runs-on: ubuntu-22.04
    timeout-minutes: 15
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@9af89fc71515a100421586dfdb3dc9c984fbf411 # v2.19.4
        with:
          egress-policy: audit

      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
        with:
          go-version-file: "go.mod"
          check-latest: true
      - uses: golang/govulncheck-action@3fa7bd9cee2cfdf3499a8803b226e43de7b7cdb4 # v1.0.4

      - name: Golang vulncheck - tools
        uses: golang/govulncheck-action@3fa7bd9cee2cfdf3499a8803b226e43de7b7cdb4 # v1.0.4
        with:
          repo-checkout: false
          work-dir: hack/tools
