name: scan_vulns

on:
  push:
    paths-ignore:
    - "docs/**"
    - "**.md"
  pull_request:
    paths-ignore:
    - "docs/**"
    - "**.md"

permissions:
  contents: read

jobs:
  govulncheck:
    name: "Run govulncheck"
    runs-on: ubuntu-22.04
    timeout-minutes: 15
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@fa2e9d605c4eeb9fcad4c99c224cee0c6c7f3594 # v2.16.0
        with:
          egress-policy: audit

      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - uses: actions/setup-go@4b73464bb391d4059bd26b0524d20df3927bd417 # v6.3.0
        with:
          go-version-file: "go.mod"
          check-latest: true
      - uses: golang/govulncheck-action@31f7c5463448f83528bd771c2d978d940080c9fd # v1.0.4

      - name: Golang vulncheck - tools
        uses: golang/govulncheck-action@31f7c5463448f83528bd771c2d978d940080c9fd # v1.0.4
        with:
          repo-checkout: false
          work-dir: hack/tools
