{{ if .Values.tokenRequests }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: secretprovidertokenrequest-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: secretprovidertokenrequest-role
subjects:
- kind: ServiceAccount
  name: secrets-store-csi-driver
  namespace: {{ .Release.Namespace }}
{{ end }}
